"""Add brand assets and asset folders tables

Revision ID: dcfcaebd1983
Revises: 
Create Date: 2025-12-28 00:41:42.652629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcfcaebd1983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_state', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('oauth_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('oauth_state', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('oauth_state', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_oauth_state_tenant'), table_name='oauth_state')
    op.drop_index(op.f('idx_oauth_state_token'), table_name='oauth_state')
    op.drop_constraint(op.f('oauth_state_state_token_key'), 'oauth_state', type_='unique')
    op.create_index(op.f('ix_oauth_state_expires_at'), 'oauth_state', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_state_state_token'), 'oauth_state', ['state_token'], unique=True)
    op.create_index(op.f('ix_oauth_state_tenant_id'), 'oauth_state', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_oauth_state_used'), 'oauth_state', ['used'], unique=False)
    op.drop_table_comment(
        'oauth_state',
        existing_comment='CSRF protection tokens for OAuth flow',
        schema=None
    )
    op.alter_column('oauth_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('oauth_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('oauth_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_oauth_tokens_last_used'), table_name='oauth_tokens')
    op.drop_index(op.f('idx_oauth_tokens_social_account'), table_name='oauth_tokens')
    op.drop_index(op.f('idx_oauth_tokens_tenant'), table_name='oauth_tokens')
    op.create_index(op.f('ix_oauth_tokens_expires_at'), 'oauth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_is_revoked'), 'oauth_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_last_used_at'), 'oauth_tokens', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_social_account_id'), 'oauth_tokens', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_tenant_id'), 'oauth_tokens', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'oauth_tokens',
        existing_comment='Encrypted OAuth tokens for social media API access',
        schema=None
    )
    op.alter_column('post_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('post_history', 'engagement_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('post_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_post_history_campaign'), table_name='post_history')
    op.drop_index(op.f('idx_post_history_social_account'), table_name='post_history')
    op.drop_index(op.f('idx_post_history_status'), table_name='post_history')
    op.drop_index(op.f('idx_post_history_tenant'), table_name='post_history')
    op.create_index(op.f('ix_post_history_campaign_name'), 'post_history', ['campaign_name'], unique=False)
    op.create_index(op.f('ix_post_history_social_account_id'), 'post_history', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_post_history_status'), 'post_history', ['status'], unique=False)
    op.create_index(op.f('ix_post_history_tenant_id'), 'post_history', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'post_history',
        existing_comment='Audit log of all social media posts',
        schema=None
    )
    op.alter_column('social_accounts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('social_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('social_accounts', 'account_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('social_accounts', 'connected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_social_accounts_active'), table_name='social_accounts')
    op.drop_index(op.f('idx_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('idx_social_accounts_tenant'), table_name='social_accounts')
    op.drop_constraint(op.f('social_accounts_tenant_id_platform_platform_account_id_key'), 'social_accounts', type_='unique')
    op.create_index('idx_social_accounts_unique', 'social_accounts', ['tenant_id', 'platform', 'platform_account_id'], unique=True)
    op.create_index(op.f('ix_social_accounts_is_active'), 'social_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_accounts_tenant_id'), 'social_accounts', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'social_accounts',
        existing_comment='Connected social media accounts (Facebook pages, Instagram accounts, etc.)',
        schema=None
    )
    op.alter_column('tenant_users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('tenant_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_tenant_users_email'), table_name='tenant_users')
    op.drop_index(op.f('idx_tenant_users_tenant'), table_name='tenant_users')
    op.drop_constraint(op.f('tenant_users_tenant_id_email_key'), 'tenant_users', type_='unique')
    op.create_index('idx_tenant_users_unique', 'tenant_users', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'tenant_users',
        existing_comment='Users who can manage tenant accounts',
        schema=None
    )
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('tenants', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('tenants', 'tenant_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_tenants_created'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_status'), table_name='tenants')
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.drop_table_comment(
        'tenants',
        existing_comment='Restaurants/businesses using the platform',
        schema=None
    )
    op.alter_column('token_refresh_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('token_refresh_history', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_token_refresh_token'), table_name='token_refresh_history')
    op.create_index(op.f('ix_token_refresh_history_oauth_token_id'), 'token_refresh_history', ['oauth_token_id'], unique=False)
    op.alter_column('webhook_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhook_events', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('webhook_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_webhook_events_tenant'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_type'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_tenant_id'), 'webhook_events', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'webhook_events',
        existing_comment='Events received from social media platforms',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'webhook_events',
        'Events received from social media platforms',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_webhook_events_tenant_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_created_at'), table_name='webhook_events')
    op.create_index(op.f('idx_webhook_events_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_webhook_events_tenant'), 'webhook_events', ['tenant_id'], unique=False)
    op.alter_column('webhook_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('webhook_events', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('webhook_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_refresh_history_oauth_token_id'), table_name='token_refresh_history')
    op.create_index(op.f('idx_token_refresh_token'), 'token_refresh_history', ['oauth_token_id'], unique=False)
    op.alter_column('token_refresh_history', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('token_refresh_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'tenants',
        'Restaurants/businesses using the platform',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('idx_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_index(op.f('idx_tenants_created'), 'tenants', ['created_at'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tenants', 'tenant_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('tenants', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'basic'::character varying"),
               nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               nullable=True)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'tenant_users',
        'Users who can manage tenant accounts',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_index('idx_tenant_users_unique', table_name='tenant_users')
    op.create_unique_constraint(op.f('tenant_users_tenant_id_email_key'), 'tenant_users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenant_users_tenant'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.alter_column('tenant_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tenant_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'admin'::character varying"),
               nullable=True)
    op.alter_column('tenant_users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'social_accounts',
        'Connected social media accounts (Facebook pages, Instagram accounts, etc.)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_social_accounts_tenant_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_is_active'), table_name='social_accounts')
    op.drop_index('idx_social_accounts_unique', table_name='social_accounts')
    op.create_unique_constraint(op.f('social_accounts_tenant_id_platform_platform_account_id_key'), 'social_accounts', ['tenant_id', 'platform', 'platform_account_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_social_accounts_tenant'), 'social_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('idx_social_accounts_active'), 'social_accounts', ['is_active'], unique=False)
    op.alter_column('social_accounts', 'connected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('social_accounts', 'account_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('social_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('social_accounts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'post_history',
        'Audit log of all social media posts',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_post_history_tenant_id'), table_name='post_history')
    op.drop_index(op.f('ix_post_history_status'), table_name='post_history')
    op.drop_index(op.f('ix_post_history_social_account_id'), table_name='post_history')
    op.drop_index(op.f('ix_post_history_campaign_name'), table_name='post_history')
    op.create_index(op.f('idx_post_history_tenant'), 'post_history', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_post_history_status'), 'post_history', ['status'], unique=False)
    op.create_index(op.f('idx_post_history_social_account'), 'post_history', ['social_account_id'], unique=False)
    op.create_index(op.f('idx_post_history_campaign'), 'post_history', ['campaign_name'], unique=False)
    op.alter_column('post_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('post_history', 'engagement_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('post_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               nullable=True)
    op.alter_column('post_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'oauth_tokens',
        'Encrypted OAuth tokens for social media API access',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_oauth_tokens_tenant_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_social_account_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_last_used_at'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_is_revoked'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_expires_at'), table_name='oauth_tokens')
    op.create_index(op.f('idx_oauth_tokens_tenant'), 'oauth_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_oauth_tokens_social_account'), 'oauth_tokens', ['social_account_id'], unique=False)
    op.create_index(op.f('idx_oauth_tokens_last_used'), 'oauth_tokens', ['last_used_at'], unique=False)
    op.alter_column('oauth_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('oauth_tokens', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('oauth_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Bearer'::character varying"),
               existing_nullable=True)
    op.alter_column('oauth_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'oauth_state',
        'CSRF protection tokens for OAuth flow',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_oauth_state_used'), table_name='oauth_state')
    op.drop_index(op.f('ix_oauth_state_tenant_id'), table_name='oauth_state')
    op.drop_index(op.f('ix_oauth_state_state_token'), table_name='oauth_state')
    op.drop_index(op.f('ix_oauth_state_expires_at'), table_name='oauth_state')
    op.create_unique_constraint(op.f('oauth_state_state_token_key'), 'oauth_state', ['state_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_oauth_state_token'), 'oauth_state', ['state_token'], unique=False)
    op.create_index(op.f('idx_oauth_state_tenant'), 'oauth_state', ['tenant_id'], unique=False)
    op.alter_column('oauth_state', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('oauth_state', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(CURRENT_TIMESTAMP + '00:10:00'::interval)"),
               existing_nullable=True)
    op.alter_column('oauth_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('oauth_state', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    # ### end Alembic commands ###
